---
- name: Copy my.cnf global MariaDB configuration.
  template:
    src: my.cnf.j2
    dest: "{{ mariadb_config }}"
    owner: root
    group: root
    mode: 0644
    force: "{{ mariadb_overwrite_global_mycnf }}"
  notify: MariaDB restart

- name: Create datadir if it does not exist
  file:
    path: "{{ mariadb_datadir }}"
    state: directory
    owner: mysql
    group: mysql
    mode: 0755
    setype: mysqld_db_t

- name: Set MariaDB service autostart.
  service:
    name: "{{ mariadb_service }}"
    state: started
    enabled: "{{ mariadb_enabled_on_startup }}"
  register: mariadb_service_configuration
