---
- name: Add MariaDB apt key
  apt_key:
    id: 'F1656F24C74CD1D8'
    keyserver: keyserver.ubuntu.com

- name: Add MariaDB apt repository
  apt_repository:
    repo: "deb http://nyc2.mirrors.digitalocean.com/mariadb/repo/{{mariadb_version}}/ubuntu {{ansible_distribution_release}} main"

- name: Install MariaDB
  apt:
    name: "{{ item }}"
  with_items: "{{ mariadb_packages }}"

- name: Start MariaDB service
  service:
    name: "{{ mariadb_service }}"    
    state: started
    enabled: yes

- name: Generate mysql config file
  template:
    src: my.cnf.j2
    dest: "{{ mariadb_config }}"
  notify: MariaDB restart

- name: Check if root password is set
  shell: mysqladmin -u root status
  changed_when: false
  failed_when: false
  register: root_password_set

- name: Set root password if not set
  mysql_user:
    name: root
    password: "{{ mariadb_root_password }}"
    host_all: yes
    state: present
  when: root_password_set.rc == 0

- name: Check if root password change is required
  shell: mysql -u root -p{{ mariadb_root_password }} -e"quit"
  changed_when: false
  failed_when: false
  when: root_password_set.rc == 1
  register: change_root_password

- name: Change root password
  shell: |
    systemctl stop {{ mariadb_service }}
    systemctl set-environment MYSQLD_OPTS="--skip-grant-tables"
    systemctl start {{ mariadb_service }}
    mysql -u root -e"UPDATE mysql.user SET password=PASSWORD('{{ mariadb_root_password }}') WHERE user='root'; FLUSH PRIVILEGES;"
    systemctl stop {{ mariadb_service }}
    systemctl unset-environment MYSQLD_OPTS
    systemctl start {{ mariadb_service }}
  when: change_root_password.rc is defined and change_root_password.rc == 1

- name: Remove 'test' database
  mysql_db:
    name: test
    login_user: root
    login_password: "{{ mariadb_root_password }}"
    state: absent

- name: Create databases
  mysql_db:
    name: "{{ item.name }}"
    collation: "{{ item.collation | default(mariadb_collation) }}"
    encoding: "{{ item.encoding | default(mariadb_charset) }}"
    login_user: root
    login_password: "{{ mariadb_root_password }}"
    state: present
  with_items: "{{ mariadb_databases }}"

- name: Remove anonymous users
  mysql_user:
    name: ''
    host_all: yes
    login_user: root
    login_password: "{{ mariadb_root_password }}"
    state: absent
  notify: MariaDB restart

- name: Create remote root user
  mysql_user:
    name: root
    password: "{{ mariadb_root_password }}"
    host: "{{ mariadb_root_remote_host }}"
    priv: "*.*:ALL,GRANT"
    login_user: root
    login_password: "{{ mariadb_root_password }}"
    state: "{{ 'absent' if mariadb_root_remote == 0 else 'present' }}"
  notify: MariaDB restart
  
- name: Create the users
  mysql_user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    host: "{{ item.host | default('localhost') }}"
    priv: "{{ item.priv }}"
    login_user: root
    login_password: "{{ mariadb_root_password }}"
    state: present
  with_items: "{{ mariadb_users }}"
  notify: MariaDB restart
